query ContentfulHomePage {
  homePage(id: "79V23p1EvX3emMjQCVJ75Z") {
    name
    featuredTokens
    notableTokens
    notableCollections
    featuredCollectionsCollection {
      items {
        name
        collectionAddress
        featureImage {
          title
          url
        }
      }
    }
    resourcesCollection {
      items {
        title
        description
        href
        isExternal
        image {
          title
          url
        }
      }
    }
  }
}
